name: index

on: 
  push:
      branches: [ master ]
  pull_request:
    branches: [ master ]

  jobs:
    test:
      run-on: ubuntu-lastest

  steps: 
    - uses: actions/checkout@v2
    - uses: actions/septup-node@v2
    with:
      node-version: '12'
    - run: npm ci
    - run: npm test
    
